const Map<String, Map<String, String>> attributeMapping = {
  'Termos personales': {
    'nombreProducto': 'Nombre del producto',
    'descripcion': 'Descripción',
    'capacidad': 'Capacidad',
    'precio': 'Precio',
    'informacion': 'Información',
    'calificacion': 'Calificación',
    'region': 'Región',
    'Diseño': 'Diseño',
    'Dimensiones': 'Dimensiones',
    'Ensambledelatapa': 'Ensamble de la tapa',
    'capacidadVerificada': 'Verificada',
    'Peso': 'Peso',
    'Hermeticidad': 'Hermeticidad',
    'Aguafria': 'Agua fría',
    'Aguacaliente': 'Agua caliente',
    'observaciones': 'Observaciones',
  },
  'Mayonesas y aderezos': {
    'nombreProducto': 'Nombre del Producto',
    'descripcion': 'Descripción',
    'precio': 'Precio',
    'contenidoEnergetico': 'Contenido Energético',
    'grasas': 'Grasas',
    'sodio': 'Sodio',
    'infAlConsumidor': 'Información al Consumidor',
    'contNeto': 'Contenido Neto',
    'carbohidratos': 'Carbohidratos',
    'proteina': 'Proteína',
    'observaciones': 'Observaciones',
  },
  'Servilletas': {
    'nombreProducto': 'Nombre del Producto',
    'descripcion': 'Descripción',
    'region': 'Región',
    'precio': 'Precio por Paquete',
    'precio_10_paq': 'Precio por 10 Paquetes',
    'contNeto': 'Contenido Neto',
    'calificacion': 'Calificación',
    'acabados': 'Acabados',
    'Resistencia_servilleta': 'Resistencia de la Servilleta',
    'Absorción_total': 'Absorción Total',
    'observaciones': 'Observaciones',
  },
  'Atún envasado': {
    'nombreProducto': 'Nombre del Producto',
    'descripcion': 'Descripción',
    'precio': 'Precio',
    'contNeto': 'Contenido Neto',
    'masaDrenada': 'Masa Drenada',
    'proteina': 'Proteína',
    'soya': 'Soya',
    'infAlConsumidor': 'Información al consumidor',
    'presentacion': 'Presentación',
    'observaciones': 'Observaciones',
    'medioDeCobertura': 'Medio De Cobertura',
  },
  'Cafeteras de goteo': {
    'nombreProducto': 'Nombre del Producto',
    'region': 'Región',
    'precio': 'Precio',
    'informacion': 'Información',
    'garantia': 'Garantía',
    'calentamiento': 'Calentamiento',
    'potenciaW': 'Potencia (W)',
    'seguridad': 'Seguridad',
    'derramamientoCafe': 'Derramamiento de Café',
    'observaciones': 'Observaciones',
    'calificacionGeneral': 'Calificación General',
  },
  'Pan de caja': {
    'nombreProducto': 'Nombre del producto',
    'descripcion': 'Descripción',
    'gramos': 'Gramos',
    'precio': 'Precio',
    'infAlConsumidor': 'Información al consumidor',
    'azucarestotales': 'Azúcares totales',
    'sodio': 'Sodio',
    'Calidadsanitaria': 'Calidad sanitaria',
    'Proteina': 'Proteína',
    'grasa': 'Grasa',
    'fibra': 'Fibra',
    'carbohidratos': 'Carbohidratos',
    'contenidoenergetico': 'Contenido energético',
    'observaciones': 'Observaciones',
  },
  'Salsa cátsup': {
    'idEstudioSalsasCatsup': 'ID Estudio',
    'nombreProducto': 'Nombre del Producto',
    'descripcion': 'Descripción',
    'precio': 'Precio',
    'contenidoEnergetico': 'Contenido Energético',
    'sodio': 'Sodio',
    'azucaresTotales': 'Azúcares Totales',
    'infAlConsumidor': 'Información al Consumidor',
    'contNeto': 'Contenido Neto',
    'carbohidratos': 'Carbohidratos',
    'observaciones': 'Observaciones',
    'colorante': 'Colorante Artificial',
    'saborizante': 'Saborizante Artificial',
  },
  'Pijamas': {
    'idEstudioPijamas': 'ID del estudio',
    'nombreProducto': 'Nombre del producto',
    'descripcion': 'Descripción',
    'precio': 'Precio',
    'categoria': 'Categoría',
    'infAlConsumidor': 'Información al consumidor',
    'calificacionGeneral': 'Calificación general',
    'acabados': 'Acabados',
    'verificacionDeTallas': 'Verificación de tallas',
    'identificacionDeFibras': 'Identificación de fibras',
    'solidezDelColor': 'Solidez del color',
  },
};
